<script setup lang="ts">
import {computed,onMounted,ref} from "vue";
import {apiGet,apiPatch,getApiErrorMessage} from "../lib/api";
import {useSessionStore} from "../stores/session";
import {useToastStore} from "../stores/toasts";
interface CompanyParameter{parameter:string;value:string|number|boolean;default_value:string|number|boolean;is_overridden:boolean;description:string;data_type:string;category:string;editable:boolean}
const session=useSessionStore(),toast=useToastStore(),parameters=ref<CompanyParameter[]>([]),loading=ref(false),search=ref(""),category=ref("ALL");
const categories=computed(()=>Array.from(new Set(parameters.value.map(p=>p.category))).sort());
const filtered=computed(()=>{const q=search.value.trim().toLocaleLowerCase();return parameters.value.filter(p=>(category.value==="ALL"||p.category===category.value)&&(!q||[p.description,p.parameter,p.category].some(v=>v.toLocaleLowerCase().includes(q))))});
const grouped=computed(()=>{const map=new Map<string,CompanyParameter[]>();for(const p of filtered.value){if(!map.has(p.category))map.set(p.category,[]);map.get(p.category)!.push(p)}return Array.from(map.entries())});
async function load(){if(!session.activeCompany)return;loading.value=true;try{parameters.value=await apiGet<CompanyParameter[]>("/company-parameters")}catch(e){toast.push(getApiErrorMessage(e),"error")}finally{loading.value=false}}
async function save(p:CompanyParameter){try{await apiPatch("/company-parameters/"+p.parameter,{value:p.value});toast.push("Parámetro guardado","success");await load()}catch(e){toast.push(getApiErrorMessage(e),"error");await load()}}
onMounted(load);
</script>
<template><div class="page-stack"><div class="card"><h2>Parámetros</h2><p class="text-secondary">Personalización funcional de {{session.activeCompany?.name}}. Podés buscar y filtrar por categoría.</p><div class="filters"><input v-model="search" placeholder="Buscar parámetro, descripción o categoría…"><select v-model="category"><option value="ALL">Todas las categorías</option><option v-for="c in categories" :key="c" :value="c">{{c}}</option></select></div></div><div v-if="loading" class="card text-muted">Cargando parámetros…</div><div v-else-if="!filtered.length" class="card empty-state">No hay parámetros que coincidan con la búsqueda.</div><section v-for="[name,items] in grouped" :key="name" class="card"><div class="category-heading"><div><h3>{{name}}</h3><span class="text-muted">{{items.length}} parámetros</span></div></div><div class="parameter-grid"><div v-for="p in items" :key="p.parameter" class="parameter-card"><div class="copy"><strong>{{p.description}}</strong><small>{{p.parameter}} · {{p.is_overridden?'personalizado':'valor general'}}</small></div><label v-if="p.data_type==='bool'" class="switch"><input v-model="p.value" type="checkbox" :disabled="!p.editable" @change="save(p)"><span></span></label><div v-else class="value"><input v-model="p.value" :type="p.data_type==='decimal'||p.data_type==='integer'?'number':'text'" :step="p.data_type==='decimal'?'0.01':undefined" :disabled="!p.editable"><button class="btn btn--ghost btn--sm" @click="save(p)">Guardar</button></div></div></div></section></div></template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:18px}.card h2,.category-heading h3{margin:0 0 6px}.filters{display:grid;grid-template-columns:minmax(240px,1fr) 260px;gap:12px;margin-top:18px}.filters input,.filters select,.value input{background:#10283f!important;color:#e5edf7!important;border:1px solid rgba(148,163,184,.35)!important}.filters input::placeholder{color:#94a3b8!important;opacity:1}.filters select option{background:#10283f;color:#e5edf7}.filters select{color-scheme:dark}.category-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.parameter-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.parameter-card{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px;border:1px solid rgba(148,163,184,.14);border-radius:12px;background:rgba(148,163,184,.04)}.copy{display:flex;flex-direction:column;gap:5px}.copy small{color:var(--text-muted,#94a3b8)}.value{display:flex;gap:8px;align-items:center}.value input{max-width:150px;background:var(--color-surface,#10283f);color:var(--color-text,#e5edf7);border:1px solid rgba(148,163,184,.3);color-scheme:dark}.value input:disabled{color:var(--color-text-muted,#94a3b8);opacity:.8}.value input::-webkit-inner-spin-button,.value input::-webkit-outer-spin-button{opacity:1}.switch input{position:absolute;opacity:0}.switch span{display:block;width:46px;height:26px;border-radius:999px;background:rgba(148,163,184,.35);position:relative;cursor:pointer}.switch span:after{content:"";position:absolute;width:20px;height:20px;left:3px;top:3px;border-radius:50%;background:white;transition:.15s}.switch input:checked+span{background:#3b82f6}.switch input:checked+span:after{transform:translateX(20px)}@media(max-width:800px){.filters,.parameter-grid{grid-template-columns:1fr}.parameter-card{align-items:flex-start;flex-direction:column}.value{width:100%}.value input{max-width:none;flex:1}}</style>