<script setup lang="ts">
import {onMounted,ref} from "vue";
import {apiGet,apiPost,getApiErrorMessage} from "../lib/api";
import {useToastStore} from "../stores/toasts";
interface Customer{id:number;name:string;phone:string|null;whatsapp:string|null}
interface Equipment{id:number;category_name:string;brand:string|null;model:string|null;serial_number:string|null}
interface Order{id:number;number:number;customer_id:number;customer_name:string;customer_phone:string|null;equipment_id:number;equipment_label:string;serial_number:string|null;received_at:string;reported_fault:string;physical_condition:string|null;accessories:string|null;notes:string|null;received_by_name:string;status:string}
interface Event{id:number;event_type:string;status:string|null;detail:string|null;user_name:string;created_at:string}
const toast=useToastStore(),orders=ref<Order[]>([]),total=ref(0),search=ref(""),customers=ref<Customer[]>([]),equipment=ref<Equipment[]>([]),selected=ref<Order|null>(null),events=ref<Event[]>([]),showReception=ref(false);
const form=ref({customer_id:0,equipment_id:0,reported_fault:"",physical_condition:"",accessories:"",notes:""});
async function load(){try{const r=await apiGet<{items:Order[];total:number}>("/work-orders",{params:{search:search.value||undefined,page_size:100}});orders.value=r.items;total.value=r.total}catch(e){toast.push(getApiErrorMessage(e,"No se pudieron cargar las órdenes"),"error")}}
async function newReception(){form.value={customer_id:0,equipment_id:0,reported_fault:"",physical_condition:"",accessories:"",notes:""};equipment.value=[];customers.value=(await apiGet<{items:Customer[]}>("/customers",{params:{active:true,page_size:100}})).items;showReception.value=true}
async function customerChanged(){form.value.equipment_id=0;equipment.value=form.value.customer_id?await apiGet<Equipment[]>("/customers/"+form.value.customer_id+"/equipment"):[]}
async function save(){try{const row=await apiPost<Order>("/work-orders",form.value);showReception.value=false;toast.push("OT #"+row.number+" generada","success");await load();await open(row)}catch(e){toast.push(getApiErrorMessage(e),"error")}}
async function open(row:Order){selected.value=await apiGet<Order>("/work-orders/"+row.id);events.value=await apiGet<Event[]>("/work-orders/"+row.id+"/events")}
function printReceipt(){window.print()}
let timer:number|undefined;function searchChanged(){window.clearTimeout(timer);timer=window.setTimeout(load,250)}
onMounted(load);
</script>
<template>
<div class="card flex flex--between" style="gap:16px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">Órdenes de trabajo</h2><p class="text-secondary" style="margin:4px 0 0">{{total}} órdenes en esta empresa</p></div><div class="toolbar"><input v-model="search" class="toolbar__search" placeholder="N° OT, cliente, teléfono, equipo o serie" @input="searchChanged"><button class="btn btn--primary" @click="newReception">+ Nueva recepción</button></div></div>
<div class="card"><table v-if="orders.length" class="table"><thead><tr><th>OT</th><th>Recepción</th><th>Cliente</th><th>Equipo</th><th>Falla informada</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="o in orders" :key="o.id"><td><strong>#{{o.number}}</strong></td><td>{{new Date(o.received_at).toLocaleString()}}</td><td>{{o.customer_name}}<div class="text-muted">{{o.customer_phone||"—"}}</div></td><td>{{o.equipment_label}}<div class="text-muted">{{o.serial_number||"Sin serie"}}</div></td><td>{{o.reported_fault}}</td><td><span class="badge badge--success">Recibido</span></td><td><button class="btn btn--ghost btn--sm" @click="open(o)">Ver</button></td></tr></tbody></table><div v-else class="empty-state">Todavía no hay órdenes de trabajo en esta empresa.</div></div>
<div v-if="selected" class="card receipt"><div class="flex flex--between"><div><p class="card__title">Orden de trabajo #{{selected.number}}</p><p class="text-secondary">{{selected.customer_name}} · {{selected.equipment_label}}</p></div><button class="btn btn--ghost no-print" @click="printReceipt">Imprimir comprobante</button></div><div class="receipt__grid"><div><strong>Falla informada</strong><p>{{selected.reported_fault}}</p></div><div><strong>Estado físico</strong><p>{{selected.physical_condition||"Sin observaciones"}}</p></div><div><strong>Accesorios</strong><p>{{selected.accessories||"Ninguno informado"}}</p></div><div><strong>Recibió</strong><p>{{selected.received_by_name}}</p></div></div><h3>Historial</h3><div v-for="e in events" :key="e.id" class="timeline"><strong>{{e.status==="RECEIVED"?"Recibido":e.event_type}}</strong><span>{{e.detail}} · {{e.user_name}} · {{new Date(e.created_at).toLocaleString()}}</span></div></div>
<div v-if="showReception" class="modal-backdrop"><div class="modal card reception-modal"><div class="flex flex--between"><h2>Nueva recepción</h2><button class="btn btn--ghost" @click="showReception=false">×</button></div><form @submit.prevent="save"><div class="field"><label>Cliente *</label><select v-model.number="form.customer_id" required @change="customerChanged"><option :value="0" disabled>Seleccionar cliente</option><option v-for="c in customers" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div class="field"><label>Equipo *</label><select v-model.number="form.equipment_id" required :disabled="!form.customer_id"><option :value="0" disabled>Seleccionar equipo</option><option v-for="e in equipment" :key="e.id" :value="e.id">{{[e.category_name,e.brand,e.model,e.serial_number].filter(Boolean).join(" · ")}}</option></select><small class="text-muted">Si el equipo es nuevo, cargalo primero desde Clientes y equipos.</small></div><div class="field"><label>Falla informada por el cliente *</label><textarea v-model="form.reported_fault" rows="3" required/></div><div class="field__row"><div class="field"><label>Estado físico</label><textarea v-model="form.physical_condition" rows="2"/></div><div class="field"><label>Accesorios entregados</label><textarea v-model="form.accessories" rows="2"/></div></div><div class="field"><label>Observaciones</label><textarea v-model="form.notes" rows="2"/></div><div class="flex flex--between" style="margin-top:18px"><button type="button" class="btn btn--ghost" @click="showReception=false">Cancelar</button><button class="btn btn--primary">Generar OT</button></div></form></div></div>
</template>
<style scoped>
.modal-backdrop{position:fixed;inset:0;z-index:100;background:rgba(2,6,23,.72);display:grid;place-items:center;padding:20px}.reception-modal{width:min(760px,100%);max-height:92vh;overflow:auto}.receipt__grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.timeline{display:flex;flex-direction:column;border-left:2px solid rgba(96,165,250,.45);padding:6px 0 12px 14px}.timeline span{color:var(--text-secondary);margin-top:3px}@media(max-width:700px){.receipt__grid{grid-template-columns:1fr}}@media print{body *{visibility:hidden}.receipt,.receipt *{visibility:visible}.receipt{position:absolute;inset:0;background:white;color:black;box-shadow:none}.no-print{display:none!important}}
</style>