<script setup lang="ts">
import {onMounted,ref} from "vue";
import {apiGet,apiPost,getApiErrorMessage} from "../lib/api";
import {useToastStore} from "../stores/toasts";
interface Customer{id:number;name:string;phone:string|null;whatsapp:string|null}
interface Equipment{id:number;category_name:string;brand:string|null;model:string|null;serial_number:string|null}
interface Order{id:number;number:number;customer_id:number;customer_name:string;customer_phone:string|null;equipment_id:number;equipment_label:string;serial_number:string|null;received_at:string;reported_fault:string;physical_condition:string|null;accessories:string|null;notes:string|null;received_by_name:string;status:string}
interface Event{id:number;event_type:string;status:string|null;detail:string|null;user_name:string;created_at:string}
const toast=useToastStore(),orders=ref<Order[]>([]),total=ref(0),search=ref(""),customers=ref<Customer[]>([]),equipment=ref<Equipment[]>([]),selected=ref<Order|null>(null),events=ref<Event[]>([]),showReception=ref(false);
const form=ref({customer_id:0,equipment_id:0,reported_fault:"",physical_condition:"",accessories:"",notes:""});
const customerQuery=ref(""),customerOpen=ref(false),showQuickCustomer=ref(false);
const quickCustomer=ref({customer_type:"PERSON",name:"",document:"",phone:"",whatsapp:"",email:"",address:"",notes:""});
interface EquipmentCategory{id:number;name:string;active:boolean}
const showQuickEquipment=ref(false),categoryQuery=ref(""),categories=ref<EquipmentCategory[]>([]),categoryOpen=ref(false);
const quickEquipment=ref({category_id:0,brand:"",model:"",serial_number:"",description:"",notes:""});
async function load(){try{const r=await apiGet<{items:Order[];total:number}>("/work-orders",{params:{search:search.value||undefined,page_size:100}});orders.value=r.items;total.value=r.total}catch(e){toast.push(getApiErrorMessage(e,"No se pudieron cargar las órdenes"),"error")}}
async function newReception(){form.value={customer_id:0,equipment_id:0,reported_fault:"",physical_condition:"",accessories:"",notes:""};equipment.value=[];customers.value=[];customerQuery.value="";customerOpen.value=false;showReception.value=true}
async function findCustomers(){customerOpen.value=true;customers.value=(await apiGet<{items:Customer[]}>("/customers",{params:{search:customerQuery.value||undefined,active:true,page_size:20}})).items}
async function chooseCustomer(c:Customer){form.value.customer_id=c.id;customerQuery.value=c.name;customerOpen.value=false;await customerChanged()}
function openQuickCustomer(){quickCustomer.value={customer_type:"PERSON",name:customerQuery.value.trim(),document:"",phone:"",whatsapp:"",email:"",address:"",notes:""};showQuickCustomer.value=true;customerOpen.value=false}
async function saveQuickCustomer(){try{const p=quickCustomer.value;const c=await apiPost<Customer>("/customers",{...p,email:p.email||null,document:p.document||null,phone:p.phone||null,whatsapp:p.whatsapp||null,address:p.address||null,notes:p.notes||null});showQuickCustomer.value=false;customers.value=[c];await chooseCustomer(c);toast.push("Cliente creado y seleccionado","success")}catch(e){toast.push(getApiErrorMessage(e),"error")}}
async function customerChanged(){form.value.equipment_id=0;equipment.value=form.value.customer_id?await apiGet<Equipment[]>("/customers/"+form.value.customer_id+"/equipment"):[]}
function openQuickEquipment(){if(!form.value.customer_id)return;quickEquipment.value={category_id:0,brand:"",model:"",serial_number:"",description:"",notes:""};categoryQuery.value="";categories.value=[];showQuickEquipment.value=true}
async function findCategories(){categoryOpen.value=true;categories.value=await apiGet<EquipmentCategory[]>("/customers/equipment-categories/search",{params:{q:categoryQuery.value}})}
function chooseCategory(cat:EquipmentCategory){quickEquipment.value.category_id=cat.id;categoryQuery.value=cat.name;categoryOpen.value=false}
function exactCategory(){return categories.value.some(c=>c.name.toLocaleLowerCase()===categoryQuery.value.trim().toLocaleLowerCase())}
async function createCategory(){const name=categoryQuery.value.trim();if(!name)return;try{const cat=await apiPost<EquipmentCategory>("/customers/equipment-categories",{name});chooseCategory(cat);toast.push("Categoría creada","success")}catch(e){toast.push(getApiErrorMessage(e),"error")}}
async function saveQuickEquipment(){if(!form.value.customer_id)return;if(!quickEquipment.value.category_id){toast.push("Seleccioná o creá una categoría","error");return}try{const e=await apiPost<Equipment>("/customers/"+form.value.customer_id+"/equipment",{customer_id:form.value.customer_id,...quickEquipment.value});showQuickEquipment.value=false;await customerChanged();form.value.equipment_id=e.id;toast.push("Equipo creado y seleccionado","success")}catch(e){toast.push(getApiErrorMessage(e),"error")}}
async function save(){try{const row=await apiPost<Order>("/work-orders",form.value);showReception.value=false;toast.push("OT #"+row.number+" generada","success");await load();await open(row)}catch(e){toast.push(getApiErrorMessage(e),"error")}}
async function open(row:Order){selected.value=await apiGet<Order>("/work-orders/"+row.id);events.value=await apiGet<Event[]>("/work-orders/"+row.id+"/events")}
function printReceipt(){window.print()}
let timer:number|undefined;function searchChanged(){window.clearTimeout(timer);timer=window.setTimeout(load,250)}
onMounted(load);
</script>
<template>
<div class="card flex flex--between" style="gap:16px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">Órdenes de trabajo</h2><p class="text-secondary" style="margin:4px 0 0">{{total}} órdenes en esta empresa</p></div><div class="toolbar"><input v-model="search" class="toolbar__search" placeholder="N° OT, cliente, teléfono, equipo o serie" @input="searchChanged"><button class="btn btn--primary" @click="newReception">+ Nueva recepción</button></div></div>
<div class="card"><table v-if="orders.length" class="table"><thead><tr><th>OT</th><th>Recepción</th><th>Cliente</th><th>Equipo</th><th>Falla informada</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="o in orders" :key="o.id"><td><strong>#{{o.number}}</strong></td><td>{{new Date(o.received_at).toLocaleString()}}</td><td>{{o.customer_name}}<div class="text-muted">{{o.customer_phone||"—"}}</div></td><td>{{o.equipment_label}}<div class="text-muted">{{o.serial_number||"Sin serie"}}</div></td><td>{{o.reported_fault}}</td><td><span class="badge badge--success">Recibido</span></td><td><button class="btn btn--ghost btn--sm" @click="open(o)">Ver</button></td></tr></tbody></table><div v-else class="empty-state">Todavía no hay órdenes de trabajo en esta empresa.</div></div>
<div v-if="selected" class="card receipt"><div class="flex flex--between"><div><p class="card__title">Orden de trabajo #{{selected.number}}</p><p class="text-secondary">{{selected.customer_name}} · {{selected.equipment_label}}</p></div><button class="btn btn--ghost no-print" @click="printReceipt">Imprimir comprobante</button></div><div class="receipt__grid"><div><strong>Falla informada</strong><p>{{selected.reported_fault}}</p></div><div><strong>Estado físico</strong><p>{{selected.physical_condition||"Sin observaciones"}}</p></div><div><strong>Accesorios</strong><p>{{selected.accessories||"Ninguno informado"}}</p></div><div><strong>Recibió</strong><p>{{selected.received_by_name}}</p></div></div><h3>Historial</h3><div v-for="e in events" :key="e.id" class="timeline"><strong>{{e.status==="RECEIVED"?"Recibido":e.event_type}}</strong><span>{{e.detail}} · {{e.user_name}} · {{new Date(e.created_at).toLocaleString()}}</span></div></div>
<div v-if="showReception" class="modal-backdrop"><div class="modal card reception-modal"><div class="flex flex--between"><h2>Nueva recepción</h2><button class="btn btn--ghost" @click="showReception=false">×</button></div><form @submit.prevent="save"><div class="field customer-picker"><label>Cliente *</label><div class="customer-picker__input"><input v-model="customerQuery" placeholder="Buscar por nombre, DNI/CUIT o teléfono…" autocomplete="off" required @focus="findCustomers" @input="form.customer_id=0;equipment=[];findCustomers()"><button type="button" class="btn btn--ghost btn--sm" @click="openQuickCustomer">+ Nuevo</button></div><div v-if="customerOpen" class="customer-picker__menu"><button v-for="c in customers" :key="c.id" type="button" class="customer-picker__option" @click="chooseCustomer(c)"><strong>{{c.name}}</strong><span>{{c.phone||c.whatsapp||"Sin teléfono"}}</span></button><button type="button" class="customer-picker__option customer-picker__create" @click="openQuickCustomer">+ Crear cliente{{customerQuery.trim()?' “'+customerQuery.trim()+'”':''}}</button></div></div><div class="field"><label>Equipo *</label><div class="customer-picker__input"><select v-model.number="form.equipment_id" required :disabled="!form.customer_id"><option :value="0" disabled>Seleccionar equipo</option><option v-for="e in equipment" :key="e.id" :value="e.id">{{[e.category_name,e.brand,e.model,e.serial_number].filter(Boolean).join(" · ")}}</option></select><button type="button" class="btn btn--ghost btn--sm" :disabled="!form.customer_id" @click="openQuickEquipment">+ Nuevo</button></div><small class="text-muted">{{form.customer_id?"Seleccioná un equipo existente o crealo sin salir de la recepción.":"Primero seleccioná o creá el cliente."}}</small></div><div class="field"><label>Falla informada por el cliente *</label><textarea v-model="form.reported_fault" rows="3" required/></div><div class="field__row"><div class="field"><label>Estado físico</label><textarea v-model="form.physical_condition" rows="2"/></div><div class="field"><label>Accesorios entregados</label><textarea v-model="form.accessories" rows="2"/></div></div><div class="field"><label>Observaciones</label><textarea v-model="form.notes" rows="2"/></div><div class="flex flex--between" style="margin-top:18px"><button type="button" class="btn btn--ghost" @click="showReception=false">Cancelar</button><button class="btn btn--primary">Generar OT</button></div></form></div></div>
<div v-if="showQuickEquipment" class="modal-backdrop quick-customer-layer"><div class="modal card reception-modal"><div class="flex flex--between"><h2>Nuevo equipo · {{customerQuery}}</h2><button class="btn btn--ghost" type="button" @click="showQuickEquipment=false">×</button></div><form @submit.prevent="saveQuickEquipment"><div class="field__row"><div class="field customer-picker"><label>Tipo / categoría *</label><input v-model="categoryQuery" placeholder="Buscar o crear categoría…" autocomplete="off" required @focus="findCategories" @input="quickEquipment.category_id=0;findCategories()"><div v-if="categoryOpen && categoryQuery.trim()" class="customer-picker__menu"><button v-for="cat in categories" :key="cat.id" type="button" class="customer-picker__option" @click="chooseCategory(cat)"><strong>{{cat.name}}</strong></button><button v-if="!exactCategory()" type="button" class="customer-picker__option customer-picker__create" @click="createCategory">+ Crear “{{categoryQuery.trim()}}”</button></div></div><div class="field"><label>Marca</label><input v-model="quickEquipment.brand"></div></div><div class="field__row"><div class="field"><label>Modelo</label><input v-model="quickEquipment.model"></div><div class="field"><label>N° de serie</label><input v-model="quickEquipment.serial_number"></div></div><div class="field"><label>Descripción</label><input v-model="quickEquipment.description"></div><div class="field"><label>Observaciones</label><textarea v-model="quickEquipment.notes" rows="2"/></div><div class="flex flex--between" style="margin-top:18px"><button type="button" class="btn btn--ghost" @click="showQuickEquipment=false">Cancelar</button><button class="btn btn--primary">Crear y seleccionar</button></div></form></div></div>
<div v-if="showQuickCustomer" class="modal-backdrop quick-customer-layer"><div class="modal card reception-modal"><div class="flex flex--between"><h2>Nuevo cliente</h2><button class="btn btn--ghost" type="button" @click="showQuickCustomer=false">×</button></div><form @submit.prevent="saveQuickCustomer"><div class="field__row"><div class="field"><label>Tipo</label><select v-model="quickCustomer.customer_type"><option value="PERSON">Persona</option><option value="COMPANY">Empresa</option></select></div><div class="field"><label>Nombre / Razón social *</label><input v-model="quickCustomer.name" required autofocus></div></div><div class="field__row"><div class="field"><label>DNI / CUIT</label><input v-model="quickCustomer.document"></div><div class="field"><label>Teléfono</label><input v-model="quickCustomer.phone"></div></div><div class="field__row"><div class="field"><label>WhatsApp</label><input v-model="quickCustomer.whatsapp"></div><div class="field"><label>Email</label><input v-model="quickCustomer.email" type="email"></div></div><div class="field"><label>Domicilio</label><input v-model="quickCustomer.address"></div><div class="flex flex--between" style="margin-top:18px"><button type="button" class="btn btn--ghost" @click="showQuickCustomer=false">Cancelar</button><button class="btn btn--primary">Crear y seleccionar</button></div></form></div></div>
</template>
<style scoped>
.modal-backdrop{position:fixed;inset:0;z-index:100;background:rgba(2,6,23,.72);display:grid;place-items:center;padding:20px}.reception-modal{width:min(760px,100%);max-height:92vh;overflow:auto}.receipt__grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.timeline{display:flex;flex-direction:column;border-left:2px solid rgba(96,165,250,.45);padding:6px 0 12px 14px}.timeline span{color:var(--text-secondary);margin-top:3px}@media(max-width:700px){.receipt__grid{grid-template-columns:1fr}}@media print{body *{visibility:hidden}.receipt,.receipt *{visibility:visible}.receipt{position:absolute;inset:0;background:white;color:black;box-shadow:none}.no-print{display:none!important}}
.customer-picker{position:relative}.customer-picker__input{display:grid;grid-template-columns:1fr auto;gap:8px}.customer-picker__menu{position:absolute;z-index:30;top:100%;left:0;right:0;margin-top:6px;padding:6px;background:var(--surface,#152238);border:1px solid rgba(148,163,184,.25);border-radius:12px;box-shadow:0 18px 45px rgba(0,0,0,.35);max-height:260px;overflow:auto}.customer-picker__option{display:flex;width:100%;align-items:center;justify-content:space-between;gap:12px;text-align:left;padding:10px 12px;border:0;border-radius:8px;background:transparent;color:inherit;cursor:pointer}.customer-picker__option span{font-size:12px;color:var(--text-secondary)}.customer-picker__option:hover{background:rgba(59,130,246,.14)}.customer-picker__create{display:block;color:#60a5fa;font-weight:700;border-top:1px solid rgba(148,163,184,.15);margin-top:4px}.quick-customer-layer{z-index:120}
</style>